version: '3.9'

networks:
  net_db:

services:
  db:
    image: mongo:4
    ports:
      - 27017:27017
    container_name: db
    restart: unless-stopped
    networks:
      - net_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=slama
      - MONGO_INITDB_ROOT_PASSWORD=IamTHEpassw0rD
      - MONGO_INITDB_DATABASE=slb

  db-view:
    image: mongo-express
    restart: unless-stopped
    container_name: db-view
    networks:
      - net_db
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=slama
      - ME_CONFIG_MONGODB_ADMINPASSWORD=IamTHEpassw0rD